### ISSUE TITLE
Doesn't work for spring-framework

### ISSUE THREAD

**Issue by tedyoung** [maciejwalkowiak/spring-docs-read-latest-extension#5]
It looks like the code is looking for `.../spring/...` and `.../spring-boot/...`. Spring Boot works fine, but the URL for the core framework is not `/spring/` but `/spring-framework/`, which the extension doesn't recognize. In `inject.js` I replaced `'spring'` with `'spring-framework'` in a local implementation and that fixes it. Would you like a PR?

**Comment by maciejwalkowiak** [comment]
@tedyoung yes please!

**Comment by tedyoung** [comment]
Will you be putting out a new release soon? If so, a link to the extension from the README would be useful (so I can point folks somewhere that's not the installer itself).

**Comment by maciejwalkowiak** [comment]
Fixed in https://github.com/maciejwalkowiak/spring-docs-read-latest-extension/pull/6.

@tedyoung release on github done, in Chrome Web Store is waiting for a review.
